# Generated by Django 5.1.1 on 2025-04-20 15:33

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "blog",
            "0005_alter_comment_options_alter_comment_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="post",
            managers=[
                ("published", django.db.models.manager.Manager()),
            ],
        ),
    ]
