# Generated by Django 5.1.1 on 2025-04-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_comment_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="is_published",
        ),
    ]
